<?php

namespace Demo\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Demo\TaskBundle\Entity\Customer;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository {

    public function customerRecord($customerName) {
        $query = $this->getEntityManager()->createQuery(
                        'SELECT count(c.id) FROM DemoTaskBundle:Customer c WHERE c.firstname = :name'
                )->setParameter('name', $customerName);

        return $query->getSingleScalarResult();
    }

    public function customerEmail($customerEmail) {
        $query = $this->getEntityManager()->createQuery(
                        'SELECT count(c.id) FROM DemoTaskBundle:Customer c WHERE c.emailaddress = :email'
                )->setParameter('email', $customerEmail);

        return $query->getSingleScalarResult();
    }

    public function customerPhone($customerPhone) {
        $query = $this->getEntityManager()->createQuery(
                        'SELECT count(c.id) FROM DemoTaskBundle:Customer c WHERE c.phonenumber = :phone'
                )->setParameter('phone', $customerPhone);

        return $query->getSingleScalarResult();
    }

}
