demo_task:
    resource: "@DemoTaskBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin  
    
shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
mawi_ajaxautocomplete:
    resource: '@MawiAjaxAutocompleteBundle/Resources/config/routing.xml'    