Demo\TaskBundle\Entity\OrderItem:
  type: entity
  table: order_item
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    amount:
      type: integer
      length: 20
    tax:
      type: integer
      length: 20
    quantity:
      type: integer
      length: 10
    total:
      type: integer
      length: 20
  manyToOne:
    product:
      targetEntity: Product
      inversedBy: orderitem
      joinColumn:
        name: product_id
        referencedColumnName: id
    purchase_order:
      targetEntity: PurchaseOrder
      inversedBy: orderitem
      joinColumn:
        name: purchaseorder_id
        referencedColumnName: id       
  lifecycleCallbacks:
    postPersist: [ uploads ]
    prePersist: [ uploading ]