Demo\TaskBundle\Entity\PurchaseOrder:
  type: entity
  repositoryClass: Demo\TaskBundle\Repository\PurchaseOrderRepository
  table: purchase_order
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    status:
      type: string
      length: 255
    order_date:
      type: datetime
  manyToOne:
    customer:
      targetEntity: Customer
      inversedBy: PurchaseOrders
      joinColumn:
        name: customer_id
        referencedColumnName: id
  oneToMany:
    orderitem:
      targetEntity: OrderItem
      mappedBy: purchase_order
      cascade: ["persist","remove"]
      orphanRemoval: true
  lifecycleCallbacks:
    prePersist: [ sendingmail ]      